name: Build AriaNg Release

on:
  push:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build standard version
        run: gulp clean build

      - name: Build bundled version
        run: gulp clean build-bundle

      - name: Package build artifacts
        run: |
          # 正确的SHA截取语法（无中文字符，表达式格式正确）
          cd dist
          zip -r ../AriaNg-Standard-${{ github.sha | substr:0:8 }}.zip .
          cd ..
          
          gulp clean build-bundle
          
          cd dist
          zip -r ../AriaNg-Bundled-${{ github.sha | substr:0:8 }}.zip .
          cd ..

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ariang-builds
          path: |
            AriaNg-Standard-*.zip
            AriaNg-Bundled-*.zip

      - name: Upload to Releases
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            AriaNg-Standard-*.zip
            AriaNg-Bundled-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
