name: Build AriaNg Release

on:
  push:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Get version from tag or package.json
        id: get_version
        run: |
          # 从标签获取版本号（如果存在）
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG_VERSION=${GITHUB_REF#refs/tags/}
            # 移除可能的 'v' 前缀
            TAG_VERSION=${TAG_VERSION#v}
            echo "VERSION=$TAG_VERSION" >> $GITHUB_ENV
          else
            # 如果没有标签，则从 package.json 获取版本号
            echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          fi
          echo "Using version: ${{ env.VERSION }}"

      - name: Build standard version
        run: gulp clean build

      - name: Package standard version
        run: |
          # 打包标准版，使用确定的版本号命名
          cd dist
          zip -r ../AriaNg-${{ env.VERSION }}.zip .
          cd ..

      - name: Build bundled version
        run: gulp clean build-bundle

      - name: Package bundled version
        run: |
          # 打包全能版（AllInOne），使用确定的版本号命名
          cd dist
          mv index.html AriaNg-${{ env.VERSION }}-AllInOne.html
          zip -r ../AriaNg-${{ env.VERSION }}-AllInOne.zip AriaNg-${{ env.VERSION }}-AllInOne.html
          cd ..

      - name: Package source code
        run: |
          # 创建源代码包，使用确定的版本号命名
          cd ..
          zip -r AriaNg/AriaNg-${{ env.VERSION }}-Source.zip AriaNg -x "AriaNg/.git/*" "AriaNg/dist/*" "AriaNg/.tmp/*" "AriaNg/*.zip"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ariang-builds
          path: |
            AriaNg-*.zip

      - name: Upload to Releases
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            AriaNg-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
