name: Build AriaNg Release

on:
  push:
    branches: [ master ]
  release:
    types: [ 创建 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build standard version
        run: gulp clean build

      - name: Package standard version
        run: |
          # 获取版本号
          VERSION=$(node -p "require('./package.json').version")
          
          # 打包标准版
          cd dist
          zip -r ../AriaNg-$VERSION.zip .
          cd ..

      - name: Build bundled version
        run: gulp clean build-bundle

      - name: Package bundled version
        run: |
          # 获取版本号
          VERSION=$(node -p "require('./package.json').version")
          
          # 打包全能版（AllInOne）
          cd dist
          mv index.html AriaNg-$VERSION-AllInOne.html
          zip -r ../AriaNg-$VERSION-AllInOne.zip AriaNg-$VERSION-AllInOne.html
          cd ..

      - name: Package source code
        run: |
          # 获取版本号
          VERSION=$(node -p "require('./package.json').version")
          
          # 创建源代码包
          cd ..
          zip -r AriaNg/AriaNg-$VERSION-Source.zip AriaNg -x "AriaNg/.git/*" "AriaNg/dist/*" "AriaNg/.tmp/*" "AriaNg/*.zip"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ariang-builds
          path: |
            AriaNg-*.zip

      - name: Upload to Releases
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            AriaNg-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
